import { ProTable, type ActionType, type ProColumns } from '@ant-design/pro-components'
import { Alert, Button, Form, Input, message, Modal, Space } from 'antd'
import { useCallback, useEffect, useRef, useState } from 'react'
import { deleteFirmware, listFirmware, updateFirmware, uploadFirmware, type Firmware, type FirmwareInput } from '../../api/admin'
import { AdminPage, ConfirmButton } from './AdminPage'
import { adminErrorMessage } from './adminErrors'

export function FirmwareManagementPage() {
  const [listError, setListError] = useState(''), [modalError, setModalError] = useState(''), [editing, setEditing] = useState<Firmware | null | undefined>(undefined), [file, setFile] = useState<File | null>(null), [saving, setSaving] = useState(false)
  const [form] = Form.useForm<FirmwareInput>()
  const actionRef = useRef<ActionType>(null), controllerRef = useRef<AbortController | null>(null), sequence = useRef(0), mounted = useRef(false)
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; sequence.current += 1; controllerRef.current?.abort() } }, [])
  const request = useCallback(async (params: { current?: number; pageSize?: number; keyword?: string }) => { const requestId = ++sequence.current; controllerRef.current?.abort(); const controller = new AbortController(); controllerRef.current = controller; setListError(''); try { const result = await listFirmware(params.keyword?.trim() || '', params.current ?? 1, params.pageSize ?? 20, { signal: controller.signal }); if (!mounted.current || controller.signal.aborted || sequence.current !== requestId) return { data: [], total: 0, success: false }; return { data: result.list, total: result.total, success: true } } catch (reason) { if (mounted.current && !controller.signal.aborted && sequence.current === requestId) setListError(reason instanceof Error ? reason.message : '固件加载失败'); return { data: [], total: 0, success: false } } }, [])
  function openEditor(firmware: Firmware | null) { setModalError(''); setEditing(firmware); setFile(null); form.setFieldsValue(firmware ? { firmwareName: firmware.firmwareName, version: firmware.version, type: firmware.type, remark: firmware.remark } : { firmwareName: '', version: '', type: '', remark: '' }) }
  function closeEditor() { if (saving) return; setModalError(''); setEditing(undefined) }
  async function save() { const input = await form.validateFields(); if (!editing && !file) { setModalError('请选择固件文件'); return } setSaving(true); setModalError(''); try { if (editing) await updateFirmware(editing.id, input); else await uploadFirmware(file as File, input); message.success(editing ? '固件已更新' : '固件已上传'); setEditing(undefined); await actionRef.current?.reload() } catch (reason) { setModalError(adminErrorMessage(reason, '固件保存失败')) } finally { setSaving(false) } }
  const columns: ProColumns<Firmware>[] = [{ title: '关键词', dataIndex: 'keyword', hideInTable: true }, { title: '固件名称', dataIndex: 'firmwareName', hideInSearch: true }, { title: '版本', dataIndex: 'version', hideInSearch: true }, { title: '类型', dataIndex: 'type', hideInSearch: true }, { title: '操作', valueType: 'option', render: (_, row) => <Space><Button onClick={() => openEditor(row)}>编辑</Button><ConfirmButton danger label="删除" title="确认删除该固件？" onConfirm={async () => { await deleteFirmware(row.id); message.success('固件已删除'); await actionRef.current?.reload() }} /></Space> }]
  return <AdminPage title="固件管理" error={listError} onRetry={() => void actionRef.current?.reload()} actions={<Button type="primary" onClick={() => openEditor(null)}>新建固件</Button>}><ProTable<Firmware> actionRef={actionRef} rowKey="id" columns={columns} request={request} scroll={{ x: 680 }} pagination={{ defaultPageSize: 20 }} options={false} search={{ labelWidth: 'auto' }} /><Modal title={editing ? '编辑固件' : '上传固件'} open={editing !== undefined} onCancel={closeEditor} onOk={save} confirmLoading={saving} okText={editing ? '保存' : '上传'} closable={!saving} maskClosable={!saving} cancelButtonProps={{ disabled: saving }} destroyOnHidden>{modalError && <Alert type="error" showIcon message={modalError} style={{ marginBottom: 16 }} />}<Form form={form} layout="vertical">{!editing && <Form.Item label="固件文件" htmlFor="firmware-file" required><Input id="firmware-file" type="file" accept=".bin,.apk" onChange={(event) => setFile(event.target.files?.[0] || null)} /></Form.Item>}<Form.Item name="firmwareName" label="固件名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="version" label="版本" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="type" label="类型" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="remark" label="说明"><Input.TextArea rows={3} /></Form.Item></Form></Modal></AdminPage>
}
