import { Button, Form, Input, message, Modal, Space, Table } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { deleteFirmware, listFirmware, updateFirmware, uploadFirmware, type Firmware, type FirmwareInput } from '../../api/admin'
import { AdminPage, ConfirmButton } from './AdminPage'
import { adminErrorMessage } from './adminErrors'

export function FirmwareManagementPage() {
  const [rows, setRows] = useState<Firmware[]>([]), [query, setQuery] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(''), [editing, setEditing] = useState<Firmware | null | undefined>(undefined), [file, setFile] = useState<File | null>(null), [saving, setSaving] = useState(false)
  const [form] = Form.useForm<FirmwareInput>()
  const load = useCallback((signal?: AbortSignal) => { setLoading(true); setError(''); return listFirmware(query, page, 20, { signal }).then((data) => { setRows(data.list); setTotal(data.total) }).catch((reason) => { if (!signal?.aborted) setError(reason instanceof Error ? reason.message : '固件加载失败') }).finally(() => { if (!signal?.aborted) setLoading(false) }) }, [page, query])
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort() }, [load])
  function openEditor(firmware: Firmware | null) { setEditing(firmware); setFile(null); form.setFieldsValue(firmware ? { firmwareName: firmware.firmwareName, version: firmware.version, type: firmware.type, remark: firmware.remark } : { firmwareName: '', version: '', type: '', remark: '' }) }
  async function save() { const input = await form.validateFields(); if (!editing && !file) { setError('请选择固件文件'); return } setSaving(true); setError(''); try { if (editing) await updateFirmware(editing.id, input); else await uploadFirmware(file as File, input); message.success(editing ? '固件已更新' : '固件已上传'); setEditing(undefined); await load() } catch (reason) { setError(adminErrorMessage(reason, '固件保存失败')) } finally { setSaving(false) } }
  return <AdminPage title="固件管理" loading={loading} error={error} onSearch={(value) => { setQuery(value.trim()); setPage(1) }} actions={<Button type="primary" onClick={() => openEditor(null)}>新建固件</Button>}><Table rowKey="id" dataSource={rows} scroll={{ x: 680 }} pagination={{ current: page, pageSize: 20, total, showSizeChanger: false, onChange: setPage }} columns={[
    { title: '固件名称', dataIndex: 'firmwareName' }, { title: '版本', dataIndex: 'version' }, { title: '类型', dataIndex: 'type' }, { title: '操作', render: (_, row) => <Space><Button onClick={() => openEditor(row)}>编辑</Button><ConfirmButton danger label="删除" title="确认删除该固件？" onConfirm={async () => { await deleteFirmware(row.id); message.success('固件已删除'); await load() }} /></Space> },
  ]} /><Modal title={editing ? '编辑固件' : '上传固件'} open={editing !== undefined} onCancel={() => setEditing(undefined)} onOk={save} confirmLoading={saving} okText={editing ? '保存' : '上传'} destroyOnHidden><Form form={form} layout="vertical">{!editing && <Form.Item label="固件文件" htmlFor="firmware-file" required><Input id="firmware-file" type="file" accept=".bin,.apk" onChange={(event) => setFile(event.target.files?.[0] || null)} /></Form.Item>}<Form.Item name="firmwareName" label="固件名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="version" label="版本" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="type" label="类型" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="remark" label="说明"><Input.TextArea rows={3} /></Form.Item></Form></Modal></AdminPage>
}
