import { Button, Form, Input, InputNumber, message, Modal, Select, Space, Switch, Table, Tabs, Tag } from 'antd'
import { useCallback, useEffect, useRef, useState } from 'react'
import { createModel, createTimbre, deleteModel, deleteTimbre, deleteVoiceResource, listModels, listProviders, listTimbres, listTtsModelOptions, listVoiceResources, setDefaultModel, setModelEnabled, updateModel, updateTimbre, type AdminResource, type ModelCreateInput, type TimbreInput, type TimbreResource } from '../../api/admin'
import { AdminPage, ConfirmButton } from './AdminPage'
import { adminErrorMessage } from './adminErrors'

const PAGE_SIZE = 20
const MODEL_TYPES = ['Memory', 'ASR', 'VAD', 'LLM', 'VLLM', 'TTS']

export function ResourceManagementPage() {
  const [active, setActive] = useState('Memory'), [query, setQuery] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [models, setModels] = useState<AdminResource[]>([]), [timbres, setTimbres] = useState<TimbreResource[]>([]), [clonedVoices, setClonedVoices] = useState<AdminResource[]>([]), [voiceSection, setVoiceSection] = useState('tts'), [ttsModels, setTtsModels] = useState<AdminResource[]>([]), [ttsModelId, setTtsModelId] = useState('')
  const [providers, setProviders] = useState<Array<{ code: string; name: string }>>([]), [editingModel, setEditingModel] = useState<AdminResource | null | undefined>(undefined), [editingTimbre, setEditingTimbre] = useState<TimbreResource | null | undefined>(undefined), [saving, setSaving] = useState(false)
  const [modelForm] = Form.useForm<ModelCreateInput & { configText?: string }>(), [timbreForm] = Form.useForm<TimbreInput>()
  const providerController = useRef<AbortController | null>(null), providerSequence = useRef(0), mounted = useRef(true)
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); try { if (active === 'timbres' && voiceSection === 'clone') { const data = await listVoiceResources(query, page, PAGE_SIZE, { signal }); setClonedVoices(data.list); setTotal(data.total) } else if (active === 'timbres') { const data = await listTimbres(ttsModelId, query, page, PAGE_SIZE, { signal }); setTimbres(data.list); setTotal(data.total) } else { const data = await listModels(active, query, page, PAGE_SIZE, { signal }); setModels(data.list); setTotal(data.total) } } catch (reason) { if (!signal?.aborted) setError(reason instanceof Error ? reason.message : '资源加载失败') } finally { if (!signal?.aborted) setLoading(false) } }, [active, page, query, ttsModelId, voiceSection])
  useEffect(() => { mounted.current = true; const controller = new AbortController(); listTtsModelOptions({ signal: controller.signal }).then((items) => { if (mounted.current) { setTtsModels(items); setTtsModelId((value) => value || items[0]?.id || '') } }).catch(() => undefined); return () => { mounted.current = false; controller.abort(); providerController.current?.abort() } }, [])
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort() }, [load])
  async function openModel(model: AdminResource | null) { providerController.current?.abort(); const controller = new AbortController(); providerController.current = controller; const sequence = ++providerSequence.current; const modelType = active; try { const options = await listProviders(modelType, { signal: controller.signal }); if (!mounted.current || controller.signal.aborted || sequence !== providerSequence.current) return; setProviders(options); setEditingModel(model); modelForm.setFieldsValue(model ? { modelType: model.type, providerCode: model.providerCode || options[0]?.code, modelCode: model.modelCode || '', modelName: model.name, isEnabled: model.enabled ? 1 : 0, isDefault: model.isDefault ? 1 : 0, docLink: model.docLink, remark: model.remark, sort: model.sort, configText: '' } : { modelType, providerCode: options[0]?.code, modelCode: '', modelName: '', isEnabled: 1, isDefault: 0, sort: 0, configText: '' }) } catch (reason) { if (!controller.signal.aborted && mounted.current && sequence === providerSequence.current) setError(adminErrorMessage(reason, '供应器加载失败')) } }
  function changeActive(value: string) { providerController.current?.abort(); providerController.current = null; providerSequence.current += 1; setActive(value); setPage(1) }
  async function saveModel() { const values = await modelForm.validateFields(); let config: Record<string, unknown> | undefined; if (values.configText?.trim()) { try { config = JSON.parse(values.configText) as Record<string, unknown> } catch { setError('配置 JSON 格式错误'); return } } setSaving(true); setError(''); try { if (editingModel) await updateModel(editingModel.id, { modelName: values.modelName, isEnabled: values.isEnabled, remark: values.remark, sort: values.sort, config }); else { const input = { ...values, config }; delete (input as { configText?: string }).configText; await createModel(input) } message.success(editingModel ? '模型已更新' : '模型已创建'); setEditingModel(undefined); await load() } catch (reason) { setError(adminErrorMessage(reason, '模型保存失败')) } finally { setSaving(false) } }
  function openTimbre(value: TimbreResource | null) { setEditingTimbre(value); timbreForm.setFieldsValue(value ? { ...value } : { name: '', languages: 'zh-CN', ttsModelId, ttsVoice: '', sort: 0, remark: '', voiceDemo: '' }) }
  async function saveTimbre() { const input = await timbreForm.validateFields(); setSaving(true); setError(''); try { if (editingTimbre) await updateTimbre(editingTimbre.id, input); else await createTimbre(input); message.success(editingTimbre ? '音色已更新' : '音色已创建'); setEditingTimbre(undefined); await load() } catch (reason) { setError(adminErrorMessage(reason, '音色保存失败')) } finally { setSaving(false) } }
  return <AdminPage title="资源管理" loading={loading} error={error} onSearch={(value) => { setQuery(value.trim()); setPage(1) }} actions={active === 'timbres' && voiceSection === 'clone' ? undefined : <Button type="primary" onClick={() => active === 'timbres' ? openTimbre(null) : void openModel(null)}>{active === 'timbres' ? '新增普通音色' : '新增模型'}</Button>}><Tabs activeKey={active} onChange={changeActive} items={[...MODEL_TYPES.map((type) => ({ key: type, label: type })), { key: 'timbres', label: '音色资源' }]} />
    {active === 'timbres' ? <Space direction="vertical" style={{ width: '100%' }}><Tabs activeKey={voiceSection} onChange={(value) => { setVoiceSection(value); setPage(1) }} items={[{ key: 'tts', label: '普通 TTS 音色' }, { key: 'clone', label: '克隆音色' }]} />{voiceSection === 'tts' ? <><Select aria-label="TTS 模型" value={ttsModelId || undefined} style={{ width: 'min(100%, 360px)' }} options={ttsModels.map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => { setTtsModelId(value); setPage(1) }} /><Table rowKey="id" dataSource={timbres} scroll={{ x: 720 }} pagination={{ current: page, total, pageSize: PAGE_SIZE, showSizeChanger: false, onChange: setPage }} columns={[{ title: '名称', dataIndex: 'name' }, { title: '语言', dataIndex: 'languages' }, { title: '编码', dataIndex: 'ttsVoice' }, { title: '操作', render: (_, row) => <Space><Button onClick={() => openTimbre(row)}>编辑</Button><ConfirmButton danger label="删除" title="确认删除该音色？" onConfirm={async () => { await deleteTimbre(row.id); message.success('音色已删除'); await load() }} /></Space> }]} /></> : <Table rowKey="id" dataSource={clonedVoices} scroll={{ x: 640 }} pagination={{ current: page, total, pageSize: PAGE_SIZE, showSizeChanger: false, onChange: setPage }} columns={[{ title: '名称', dataIndex: 'name' }, { title: '训练状态', render: (_, row) => row.enabled ? '可用' : '处理中' }, { title: '说明', dataIndex: 'remark' }, { title: '操作', render: (_, row) => <ConfirmButton danger label="删除" title="确认删除该克隆音色？" onConfirm={async () => { await deleteVoiceResource(row.id); message.success('克隆音色已删除'); await load() }} /> }]} />}</Space>
      : <Table rowKey="id" dataSource={models} scroll={{ x: 980 }} pagination={{ current: page, total, pageSize: PAGE_SIZE, showSizeChanger: false, onChange: setPage }} columns={[{ title: '名称', dataIndex: 'name' }, { title: '编码', dataIndex: 'modelCode' }, { title: '状态', render: (_, row) => <Tag color={row.enabled ? 'green' : 'default'}>{row.enabled ? '启用' : '停用'}</Tag> }, { title: '默认', render: (_, row) => row.isDefault ? '是' : '否' }, { title: '角色使用', dataIndex: 'profileUsageCount', render: (value) => value ?? 0 }, { title: '设备使用', dataIndex: 'deviceUsageCount', render: (value) => value ?? 0 }, { title: '操作', render: (_, row) => <Space><Button onClick={() => void openModel(row)}>编辑</Button><ConfirmButton label={row.enabled ? '停用' : '启用'} title="确认修改模型状态？" onConfirm={async () => { await setModelEnabled(row.id, !row.enabled); await load() }} /><ConfirmButton label="设为默认" title="确认设为默认模型？" disabled={row.isDefault} onConfirm={async () => { await setDefaultModel(row.id); await load() }} /><ConfirmButton danger label="删除" title="确认删除该模型？" onConfirm={async () => { await deleteModel(row.id); await load() }} /></Space> }]} />}
    <Modal title={editingModel ? '编辑模型' : '新增模型'} open={editingModel !== undefined} onCancel={() => setEditingModel(undefined)} onOk={saveModel} confirmLoading={saving} destroyOnHidden><Form form={modelForm} layout="vertical"><Form.Item name="modelType" label="类别（仅创建时设置）"><Input disabled /></Form.Item><Form.Item name="providerCode" label="供应器（仅创建时设置）" rules={[{ required: true }]}><Select disabled={Boolean(editingModel)} options={providers.map((item) => ({ value: item.code, label: item.name }))} /></Form.Item><Form.Item name="modelCode" label="模型编码（仅创建时设置）" rules={[{ required: true }]}><Input disabled={Boolean(editingModel)} /></Form.Item><Form.Item name="docLink" label="文档地址（仅创建时设置）"><Input disabled={Boolean(editingModel)} /></Form.Item><Form.Item name="modelName" label="模型名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="isEnabled" label="启用" valuePropName="checked" getValueProps={(value) => ({ checked: value === 1 })} getValueFromEvent={(checked) => checked ? 1 : 0}><Switch /></Form.Item><Form.Item name="configText" label="配置 JSON（留空不读取或覆盖密钥）"><Input.TextArea rows={5} /></Form.Item><Form.Item name="remark" label="备注"><Input /></Form.Item><Form.Item name="sort" label="排序"><InputNumber min={0} /></Form.Item><Form.Item name="isDefault" hidden><InputNumber /></Form.Item></Form></Modal>
    <Modal title={editingTimbre ? '编辑音色' : '新增音色'} open={editingTimbre !== undefined} onCancel={() => setEditingTimbre(undefined)} onOk={saveTimbre} confirmLoading={saving} destroyOnHidden><Form form={timbreForm} layout="vertical"><Form.Item name="ttsModelId" label="TTS 模型" rules={[{ required: true }]}><Select options={ttsModels.map((item) => ({ value: item.id, label: item.name }))} /></Form.Item><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="ttsVoice" label="音色编码" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="languages" label="语言" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="voiceDemo" label="试听地址"><Input /></Form.Item><Form.Item name="remark" label="备注"><Input /></Form.Item><Form.Item name="sort" label="排序"><InputNumber min={0} /></Form.Item></Form></Modal>
  </AdminPage>
}
