import { ProTable, type ActionType, type ProColumns } from '@ant-design/pro-components'
import { Alert, Button, Form, Input, message, Modal, Space, type FormInstance } from 'antd'
import { useCallback, useEffect, useRef, useState } from 'react'
import { createTemplate, deleteTemplate, listTemplates, updateTemplate, type AdminTemplate, type TemplateInput } from '../../api/admin'
import { AdminPage, ConfirmButton } from './AdminPage'
import { adminErrorMessage } from './adminErrors'

function TemplateFormInitializer({ form, template }: { form: FormInstance<TemplateInput>, template: AdminTemplate | null }) {
  useEffect(() => { form.setFieldsValue(template ? { agentCode: template.agentCode || '', agentName: template.agentName, systemPrompt: template.systemPrompt } : { agentCode: '', agentName: '', systemPrompt: '' }) }, [form, template])
  return null
}

export function TemplateManagementPage() {
  const [listError, setListError] = useState(''), [modalError, setModalError] = useState(''), [editing, setEditing] = useState<AdminTemplate | null | undefined>(undefined), [saving, setSaving] = useState(false)
  const [form] = Form.useForm<TemplateInput>()
  const actionRef = useRef<ActionType>(null), controllerRef = useRef<AbortController | null>(null), sequence = useRef(0), mounted = useRef(false)
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; sequence.current += 1; controllerRef.current?.abort() } }, [])
  const request = useCallback(async (params: { current?: number; pageSize?: number; keyword?: string }) => { const requestId = ++sequence.current; controllerRef.current?.abort(); const controller = new AbortController(); controllerRef.current = controller; setListError(''); try { const result = await listTemplates(params.keyword?.trim() || '', params.current ?? 1, params.pageSize ?? 20, { signal: controller.signal }); if (!mounted.current || controller.signal.aborted || sequence.current !== requestId) return { data: [], total: 0, success: false }; return { data: result.list, total: result.total, success: true } } catch (reason) { if (mounted.current && !controller.signal.aborted && sequence.current === requestId) setListError(reason instanceof Error ? reason.message : '模板加载失败'); return { data: [], total: 0, success: false } } }, [])
  function openEditor(template: AdminTemplate | null) { setModalError(''); setEditing(template) }
  function closeEditor() { if (saving) return; setModalError(''); form.resetFields(); setEditing(undefined) }
  async function save() { const input = await form.validateFields(); setSaving(true); setModalError(''); try { if (editing) await updateTemplate(editing.id, input); else await createTemplate(input); message.success(editing ? '模板已更新' : '模板已创建'); form.resetFields(); setEditing(undefined); await actionRef.current?.reload() } catch (reason) { setModalError(adminErrorMessage(reason, '模板保存失败')) } finally { setSaving(false) } }
  const columns: ProColumns<AdminTemplate>[] = [{ title: '关键词', dataIndex: 'keyword', hideInTable: true }, { title: '模板名称', dataIndex: 'agentName', hideInSearch: true }, { title: '模板代码', dataIndex: 'agentCode', hideInSearch: true }, { title: '说明', dataIndex: 'description', ellipsis: true, hideInSearch: true }, { title: '排序', dataIndex: 'sort', hideInSearch: true }, { title: '操作', valueType: 'option', render: (_, row) => <Space><Button onClick={() => openEditor(row)}>编辑</Button><ConfirmButton danger label="删除" title="确认删除该模板？" onConfirm={async () => { await deleteTemplate(row.id); message.success('模板已删除'); await actionRef.current?.reload() }} /></Space> }]
  return <AdminPage title="角色模板" error={listError} onRetry={() => void actionRef.current?.reload()} actions={<Button type="primary" onClick={() => openEditor(null)}>新建模板</Button>}><ProTable<AdminTemplate> actionRef={actionRef} rowKey="id" columns={columns} request={request} scroll={{ x: 680 }} pagination={{ defaultPageSize: 20 }} options={false} search={{ labelWidth: 'auto' }} /><Modal title={editing ? '编辑模板' : '新建模板'} open={editing !== undefined} onCancel={closeEditor} onOk={save} confirmLoading={saving} okText="保存" closable={!saving} maskClosable={!saving} cancelButtonProps={{ disabled: saving }} destroyOnHidden>{editing !== undefined && <>{modalError && <Alert type="error" showIcon message={modalError} style={{ marginBottom: 16 }} />}<Form form={form} layout="vertical" clearOnDestroy><TemplateFormInitializer form={form} template={editing} /><Form.Item name="agentCode" label="模板代码" rules={[{ required: true }]}><Input disabled={Boolean(editing)} /></Form.Item><Form.Item name="agentName" label="模板名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="systemPrompt" label="角色设定"><Input.TextArea rows={6} maxLength={10000} /></Form.Item></Form></>}</Modal></AdminPage>
}
