# 生产镜像，仅包含应用代码
FROM ghcr.io/xinnan-tech/xiaozhi-esp32-server:server-base

COPY main/xiaozhi-server .
COPY main/shared ./server/main/shared
COPY main/manager-web/public/generator/static/multinet_model/fst ./models/wake_word/fst
COPY main/manager-web/public/generator/static/multinet_model/mn7_cn ./models/wake_word/mn7_cn
RUN touch ./server/__init__.py ./server/main/__init__.py \
    && pip install --no-cache-dir pypinyin==0.54.0

# 启动应用
CMD ["python", "app.py"]
