#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERIAL_PORT="${SERIAL_PORT:-/dev/cu.usbmodem2101}"
LOCAL_GATEWAY_HOST="${LOCAL_GATEWAY_HOST:-192.168.0.102}"
OLD_GATEWAY_HOST="${OLD_GATEWAY_HOST:-192.168.0.110}"
LOCAL_GATEWAY_PORT="${LOCAL_GATEWAY_PORT:-1883}"
OLD_GATEWAY_PORT="${OLD_GATEWAY_PORT:-1883}"
NVS_BACKUP_DIR="$REPO_ROOT/.codex-tmp/device-nvs-backup"

banner "AI Plush Companion device recovery"

stage "Read-only environment check"
say "This wizard only inspects the host and device state. It never flashes, erases, or writes NVS."
step "Verify the repository and local services are the intended ones."
printf '  repository: %s\n' "$REPO_ROOT"
printf '  serial port: %s\n' "$SERIAL_PORT"
printf '  local gateway: %s:%s\n' "$LOCAL_GATEWAY_HOST" "$LOCAL_GATEWAY_PORT"
printf '  old gateway: %s:%s\n' "$OLD_GATEWAY_HOST" "$OLD_GATEWAY_PORT"
for command_name in curl lsof; do
  if command -v "$command_name" >/dev/null 2>&1; then
    printf '  %s: available\n' "$command_name"
  else
    warn "$command_name is not installed"
  fi
done
pause "Press Enter after confirming these values"

stage "Identify the physical device"
if [[ -e "$SERIAL_PORT" ]]; then
  say "The configured USB serial device exists."
  ls -l "$SERIAL_PORT"
else
  warn "Serial device is not present at $SERIAL_PORT"
fi
step "With the device connected, open its serial monitor at 115200 baud and reboot it manually."
step "Record the board SKU, MAC, firmware version, partition table and the MQTT endpoint from the startup log."
note "The historical bread MAC is 9c:13:9e:8a:14:a4. The device currently attached in the verified session was zhengchen MAC 7c:0c:5f:40:49:54 and already reported the local endpoint 192.168.0.102. Do not assume the two devices are the same."
pause "Press Enter after recording the startup block"

stage "Compare network paths"
say "The next checks are read-only TCP probes."
if nc -vz -G 2 "$LOCAL_GATEWAY_HOST" "$LOCAL_GATEWAY_PORT" >/dev/null 2>&1; then
  printf '  local gateway %s:%s: reachable\n' "$LOCAL_GATEWAY_HOST" "$LOCAL_GATEWAY_PORT"
else
  warn "local gateway $LOCAL_GATEWAY_HOST:$LOCAL_GATEWAY_PORT is not reachable"
fi
if nc -vz -G 2 "$OLD_GATEWAY_HOST" "$OLD_GATEWAY_PORT" >/dev/null 2>&1; then
  printf '  old gateway %s:%s: reachable\n' "$OLD_GATEWAY_HOST" "$OLD_GATEWAY_PORT"
else
  warn "old gateway $OLD_GATEWAY_HOST:$OLD_GATEWAY_PORT is not reachable"
fi
note "A reachable ping is not enough: the device needs TCP 1883 and the OTA HTTP service."
pause "Press Enter after reviewing the network result"

stage "Confirm NVS protection"
if [[ -d "$NVS_BACKUP_DIR" ]] && find "$NVS_BACKUP_DIR" -type f -print | head -n 1 | grep -q .; then
  say "An existing NVS backup directory was found: $NVS_BACKUP_DIR"
  find "$NVS_BACKUP_DIR" -type f -print | sort
else
  warn "No NVS backup was found in $NVS_BACKUP_DIR"
fi
step "Before any human flashing, make a fresh backup of partition offset 0x9000 and verify its size."
step "Keep the backup outside the firmware image and never use a merged binary containing blank NVS on a bound device."
pause "Press Enter after confirming the backup plan"

stage "Choose a manual recovery path"
say "The wizard stops before any irreversible action. Choose one path manually and record it in the acceptance log."
say "Preferred path: restore the device's MQTT/OTA endpoint through an available management or provisioning channel, then reboot and confirm the new endpoint in serial output."
say "Fallback path: use the board-specific release procedure with a verified NVS backup, flashing only the documented bootloader, partition table, OTA data, application and generated assets."
warn "Do not run an erase command or flash a full merged binary from this wizard."
if confirm "Have you completed the manual recovery and rebooted the device?"; then
  say "Re-run this wizard, then run the daytime acceptance checklist only after the serial MAC and gateway client ID match."
else
  say "No recovery was recorded. Leave the device unchanged and resolve the network path first."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
